name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run tests
      run: |
        sudo apt-get install uv
        uv pip install -e .

  repo-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Check config
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install "sp-repo-review[cli]"
        repo-review .
