name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Run tests
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv pip install -e . --system

  repo-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Check config
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install "sp-repo-review[cli]"
        repo-review .
